name: lidarcap
channels:
  - nvidia/label/cuda-12.9.1
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - google-sparsehash
  - cuda-toolkit
  - python=3.12
  - pip:
    - cuda-toolkit[all]==12.9.1
    - h5py
    - joblib
    - matplotlib
    - opencv-python
    - pandas
    - pillow
    - plyfile
    - psutil
    - pyransac3d
    - requests
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - tensorflow
    - torch
    - torchaudio
    - torchvision
    - tqdm
    - timm
    - wandb
    - yacs
