# 数据集配置
TrainDataset:
  dataset_path: '/media/yun/41306b47-5fbd-4e11-a4f8-13c59e123adf1/lidarhuman26M/lidarcap_train.hdf5'
  use_aug: false
  use_rot: false
  concat_info: false
  use_straight: false
  use_pc_w_raw_z: false
  ret_raw_pc: true
  seqlen: 16
  drop_first_n: 0
  use_trans_to_normalize: true
  replace_noice_pc: false
  replace_noice_pc_rate: false
  replace_pc_strategy: 'random'
  noise_distribution: 'uniform'
  add_noice_pc: false
  set_body_label_all_one: false
  random_permutation: false
  use_boundary: false
  inside_random: false
  use_sample: false
  range_image: false
  range_image_W: 512
  range_image_H: 512
  fov_up: 12.5
  dataset_ids:
    - lidarcap_train

TestDataset:
  dataset_path: '/media/yun/41306b47-5fbd-4e11-a4f8-13c59e123adf1/lidarhuman26M/lidarcap_test.hdf5'
  use_aug: false
  concat_info: false
  use_rot: false
  use_straight: false
  use_pc_w_raw_z: false
  ret_raw_pc: true
  seqlen: 16
  drop_first_n: 0
  use_trans_to_normalize: true
  replace_pc_strategy: 'random'
  replace_noice_pc: false
  replace_noice_pc_rate: false
  noise_distribution: 'uniform'
  add_noice_pc: false
  set_body_label_all_one: false
  random_permutation: false
  use_boundary: false
  inside_random: false
  use_sample: false
  range_image: false
  range_image_W: 512
  range_image_H: 512
  fov_up: 12.5
  dataset_ids:
    - lidarcap_test
